spring:
  application:
    name: severbusiness # 项目名称

   cloud:
      nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml # 假如不配置，则nacos远程配置文件的后缀为.properties
      discovery:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
    profiles:
      active: dev