spring:
  profiles:
    active: dev
zuul:
  routes:
    api-user:
      path: /api-user/**
      serviceId: sever-user
      #sensitiveHeaders：会过滤客户端请求中的和该配置项匹配的headers
      #zuul.ignoredHeaders会过滤服务之间通信附带的headers
    api-stock:
      path: /api-stock/**
      serviceId: sever-stock

